import type { Metadata } from "next";
import Navbar from "@/components/Navigation/Navbar";
import "./globals.css";
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="font-sans"
      >
      <Toaster
      position="top-right"
      toastOptions={{
        duration: 4000,
        style: {
          fontSize: '0.875rem',
          borderRadius: '8px',
        },
      }}
    />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
